### ISSUE TITLE
Example Final Assignments

### ISSUE THREAD

**Issue by ndwilliams01** [Watts-College/cpp-526-spr-2023#13]
Would it be possible to get previous examples of the final code-through project and final dashboard? Like those submitted for this class in the past?

**Comment by drcarlson-asu** [comment]
Great question!
Since this is my first semester teaching this course, I do not have any previous samples to share. I'll inquire with some folks to see if this is something we can get for you.
~Dr. C

**Comment by ndwilliams01** [comment]
Thank you!

**Comment by drcarlson-asu** [comment]
Hello!
I did not forget you. :)
It looks like there might be 1-2 examples available, but we haven't been able to get student permission in order to share. So, it looks like you're on your own. That's ok though as these types of projects should be very individualized to you as a student and what you know/have learned. 
~Dr. C
